### ISSUE TITLE
Consider adding example on how to implement stream directory

### ISSUE THREAD

**Issue by yevhen** [yevhen/Streamstone#10]

**Comment by jkonecki** [comment]
As a user of Streamstone I would like to retrieve the list of 
- all the existing streams
- all the streams in certain partition.

**Comment by yevhen** [comment]
Hi @jkonecki!

I finally found time to resolve this issue.
Hope, you will find the description below helpful.

There 3 possible approaches for how can you build and maintain stream directory, depending on how you partition your streams:
1. Multiple streams per single physical partition (virtual partitions) using stream properties.
2. Multiple streams per single physical partition (virtual partitions) using inline projections.
3. Single stream per physical partition using the layer of indirection

The **1)** is the simplest one. You just need to create additional stream metadata column and then you can simply query on it. See example [here](https://github.com/yevhen/Streamstone/blob/master/Source/Example/Scenarios/S10_Stream_directory.cs#L21).

 It's also the slowest approach of all, since all rows in a partition need to scanned. Still, I think it will perform quite well for majority of apps as there won't be too many rows in a single physical partition. 

The **2)** approach is a bit more complex, since you will need to track the start of lifecycle of the stream and include projection of its header. The projection row will be simply a reverse rowkey of stream header entity, so that you can query a range of rows using prefix query. See example [here](https://github.com/yevhen/Streamstone/blob/master/Source/Example/Scenarios/S10_Stream_directory.cs#L40).

This is the most performant way to query all streams (headers) in a single physical partition. There is no any other approach which is more performant than this one. The only downside, it could only be used along with `Stream.Write` since at the moment Streamstone doesn't support inclusion of additional entities when provisioning streams.

And for **3)** you may simply create a facade through which all stream operations will go. Behind the curtain, you will record (track) all created streams in some dedicated partition, so that you can simply query single partition to get information about all streams in your system. Basically, it's a just an implementation of multi-tenancy. See example [here](https://github.com/yevhen/Streamstone/blob/master/Source/Example/Scenarios/S10_Stream_directory.cs#L61)

The last approach is little bit more involved but with stream-per-partition it is the only possible approach. There will be some additional complexity related to maintaining consistency between directory partition and actual stream partition, since there is no cross-partition transactions in WATS. But I do think it's a really rare case (failure to write stream after recording it in directory) and can be resolved with manual intervention.

Have I answered your question? :smile:

**Comment by jkonecki** [comment]
Yes, thank you!
