### ISSUE TITLE
Partition key and row key are not trimmed

### ISSUE THREAD

**Issue by jkonecki** [yevhen/Streamstone#20]
Reported by @aprooks through gitter:

Partition key and row keys are not trimmed. Got extra spaces for "partition | stream" pattern
`PartitionKey = "partitionPrefix ";`
`RowKey = " 0|SS-HEAD";`
`RowType = "Stream";`
`Timestamp = 21.08.2015 19:05:45 +00:00;`

https://gitter.im/yevhen/Streamstone?at=55d7781c4eff2e77653840b1

http://prntscr.com/87btca

**Comment by jkonecki** [comment]
Based on the screenshot of F# code it looks like @aprooks constructs stream key with spaces around pipe in line:

`|> Seq.map (sprintf "%s | %d" "partitionPrefix")`

I'll create a PR with trimming for such a case.

**Comment by jkonecki** [comment]
Thinking about this change I believe we should leave the code as it is and do not trim whitespaces.
My reasoning is that the trimming just Partition Key and Row Key will leave the whole Key (and other keys) out of sync (also `.ToString()`) - that can cause confusion. Unless we trim the content of the Key itself.

I think if the user provided spaces in the stream name those should be treated as meaningful and not removed.

**Comment by aprooks** [comment]
You have confirmed some of my thoughts. Most probably I would expect only separate values to be trimmed. Like if we provide createKeyOf("prefix   ","  stream  ") values would be "prefix" and stream. 

But I still have a feeling, that a situation when you could easily end up with non-trimmed keys in  a storage could lead to some very nasty bugs.

**Comment by jkonecki** [comment]
Another option is to introduce two constructors:

`public Partition(CloudTable table, string partitionKey)`
`public Partition(CloudTable table, string partitionKey, string rowKeyPrefix)`

and trim input values.

Or use optional parameters instead of overload:

`public Partition(CloudTable table, string partitionKey, string rowKeyPrefix = "")`

**Comment by aprooks** [comment]
sounds good. 

What do you think about following to distinguish 2 ways even more?

```
var virtual = Partition.Virtual(table, "tenant1","stream-123");
var streamPerPartition = Partition.Partitioned(table,"stream-123");  //names are ugly here :(
```

**Comment by jkonecki** [comment]
Nice! Need to wait for @yevhen to decide.

**Comment by yevhen** [comment]
@jkonecki 

> Thinking about this change I believe we should leave the code as it is and do not trim whitespaces.

I think the same.

> I think if the user provided spaces in the stream name those should be treated as meaningful and not removed.

Exactly. I hate when stuff got changed behind my back without my permission. For that reason I always use `core.autocrlf = false` in Git.

@aprooks 

> But I still have a feeling, that a situation when you could easily end up with non-trimmed keys in a storage could lead to some very nasty bugs. 

Yes. But think about it from the other angle. If we automatically trim user provided key we can give him the same troubles, breaking his original intent. That also breaks the "Principle of Least Surprise" which good API should respect.
