### ISSUE TITLE
Method not found: Microsoft.WindowsAzure.Storage.Table.TableOperation.Retrieve

### ISSUE THREAD

**Issue by pawelpawlow** [yevhen/Streamstone#22]
Streamstone doesn't work with WindowsAzure.Storage 6.1.0 because Retrieve() signature has changed (has new optional parameter) and is now binary incompatible with previous versions of the library.
@yevhen, would you please update nuget references (at least WindowsAzure.Storage to v. 6.1.0), recompile and publish new Streamstone nuget.

**Comment by pawelpawlow** [comment]
That was fast :) Can you please publish the nuget package as well?

**Comment by yevhen** [comment]
already!

**Comment by pawelpawlow** [comment]
thanks :)
