### ISSUE TITLE
S09_Handling_duplicates returns a null reference exception

### ISSUE THREAD

**Issue by danialwestmorland** [yevhen/Streamstone#31]
When running the example S09_Handling_duplicates the expected exception should be DuplicateEventException. However, when running the example myself I get a NullReferenceException:

![image](https://cloud.githubusercontent.com/assets/9944657/21742631/d42b477a-d4ea-11e6-8bc8-289f48ff9b1d.png)

It looks like 'exception.RequestInformation.ExtendedErrorInformation' is null and there's no path that can handle this.

Below is a like to the example:
[https://github.com/yevhen/Streamstone/blob/master/Source/Example/Scenarios/S09_Handling_duplicates.cs](url)

**Comment by yevhen** [comment]
Which Azure SDK version? Running against local storage emulator? Version?

**Comment by danialwestmorland** [comment]
I'm running it with Microsoft Azure Storage Emulator with the following versions:

- Microsoft Azure SDK 2.9.6
- Microsoft Azure Storage Emulator 4.6.0.0

Both of these are the latest versions from Microsoft.

**Comment by yevhen** [comment]
that could be a source of problem. I haven't tested code with those versions. Try running test suite

**Comment by yevhen** [comment]
@danialwestmorland update emulator to 5.1 https://github.com/Azure/azure-storage-net/issues/408#issuecomment-284915540
