### ISSUE TITLE
Batching support

### ISSUE THREAD

**Issue by baluubas** [yevhen/Streamstone#32]
Hi,

In a project I'm currently working on I've come across a scenario where batching support could possible save a lot of roundtrips. 

My scenario is this: I have an partition/stream for each `CustomerAccount`, this corresponds to an aggregate root which have a `balance` property. In my domain I have commands that affect the balance of nearly all `CustomerAccounts`. Currently I open a stream and write an event for each customer. It would be great features if it was possible to open a batch `CustomerAccount` and write the events simultaneously to reduce number of read and writes, or rather the network overhead of doing it individually.

I have only glanced at the code, so I have no clue if this would make sense the way things are being done. Perhaps there are alternative ways of accomplishing the same thing? Anyways, just putting it out there so consider this a feature suggestion.

-Anders

**Comment by jkonecki** [comment]
How are you processing the command that affects a huge number of
aggregates? I assume you send a command to each aggregate - and each
aggregate can accept or reject this command.
How do yo see batching working across multiple aggregates? How would you
collect the events to batch from multiple aggregates? Are your aggregates
distributed across several machines?

**Comment by baluubas** [comment]
I'm using something similar to the CommonDomain repository interface that was described here https://geteventstore.com/blog/20130220/getting-started-part-2-implementing-the-commondomain-repository-interface/. 

This might be the wrong approach but I have a single command (basically containing a huge list of CustomerAccount id's) and command handler that updates all aggregates (using the repository as in the CommonDomain repository examples).

On top of my head, I would probably need an overload of Stream.ReadAsync() that take a list of partitions, to build multiple aggregates. Stream.WriteAsync() would need this overload too (I know this might not be possible but that is the best analogy I have).

I guess I would need to collect events differently, making a new type of repository for dealing batch updates. Aggregates are all on the same machine.

**Comment by yevhen** [comment]
Batching is supported per single stream, but not across streams. Table storage doesn't support cross-partition writes.

**Comment by baluubas** [comment]
I figured that there could be some limitation like this :(

The stream approach is fine. I'm just a bit worried that since these bursts of requests might cause problems with the scaling limits and cause timeouts as the service load balances out tables. Not sure this is an actual problem, more of a premature optimisation.

**Comment by yevhen** [comment]
You need to redesign your approach. Does your batch need to be transactional? If no - simply put all commands contained in a batch into a queue and then process one-by-one. If yes - ask why? Perhaps your aggregates have wrong boundaries, or maybe there is a requirement misinterpretation

**Comment by yevhen** [comment]
You can also use Competing Consumers pattern to scale queue processing
