### ISSUE TITLE
1.1 Nuget - Dependecy and .net version - mixed messages

### ISSUE THREAD

**Issue by perokvist** [yevhen/Streamstone#33]
I seems that the release statment and the nuspec tell different stories.
nuspec has a net45 folder and a dependency on Storage 7.2.1.
The release notes says that is build targeting 461 and Storage 8.X .
I get errors using 1.1 due to that the dll seems to ref 8.X but the nuget installs 7.2.1.

**Comment by yevhen** [comment]
Right. My bad. Fixed. Grab v1.1.1
