### ISSUE TITLE
Q: Does StreamStone support in-memory testing like EventStore's embedded IEventStoreConnection ?

### ISSUE THREAD

**Issue by mmisztal1980** [yevhen/Streamstone#34]
As title says, I'm starting to play around with Streamstone and I'd like to write some tests that don't require my azure storage emulator to run all the time?

I think EventStore supports it via the `EventStore.Client.Embedded` package. Does Streamstone have a similar feature?

Best regards,
Maciej

**Comment by yevhen** [comment]
Nope. Running tests against local storage emulator is extremely fast. Why do you need that? What problem will it solve?

**Comment by mmisztal1980** [comment]
This would mostly serve test automation. Some of our CI environments are managed by folks who are extremely reluctanct to install anything but msbuild, targeting packs and sdks :) we prefer to be able to cut ourselves from our umderlying infrastructure.

**Comment by yevhen** [comment]
Well, in this case you can simply test your aggregates against mock (create simple interface for SS stream writes/reads), but I think it's better to test against real infra. Up to you.
