### ISSUE TITLE
Support netstandard 1.4

### ISSUE THREAD

**Issue by 2moveit** [yevhen/Streamstone#40]
Hi, is it possible to support netstandard 1.4 or less? I saw that you already removed support for ns16.
I have problems referencing the ns 2.0/1.6 in my net461 project. 
Supporting a lower netstandard version would also target a bigger range of plattforms. As far as all APIs are available that shouldn't effect your work and the user can decide what version he takes as all are shipped in the nuget package. Or is there any other reason why you just want to target ns2.0 in the future?

**Comment by yevhen** [comment]
You can try SS 1.x. It's built against full .net. There were no substantial changes between 1.x and 2.x except targeting and removal of sync apis.

**Comment by yevhen** [comment]
NUnit3 adapter is only available for netstd20. But maybe we can multi-target at package build time. I've tried multi-targeting and it was confusing R# at the time. It might be fixed in newer versions but I haven't tried.

**Comment by 2moveit** [comment]
Yes, SS 1.x works fine. I just want to stay on the latest version to avoid later migations with more trouble and it makes contributing easier.

**Comment by yevhen** [comment]
Just stay away from sync methods and you should be fine.

**Comment by yevhen** [comment]
netstandard20 support has been addressed in version 2.0
