### ISSUE TITLE
[Question/Possible bug] Is it intended not to support Nullable<DateTime> in PropertyMap?

### ISSUE THREAD

**Issue by chyczewski-maciej** [yevhen/Streamstone#50]
Sorry if I'm asking a dumb question here. I have no broad picture of the project's implementation.

I found an anomaly in this method. All struct types are supported together with their Nullable representations. The only exception is DateTime - **DateTime?** is not supported. 
Is it intended? 

Code currently exists here:
https://github.com/yevhen/Streamstone/blob/08f59f66898358f24b51b7c250b56ae0d51ed865/Source/Streamstone/PropertyMap.cs#L103-L133

Code was originally introduced here: 
https://github.com/yevhen/Streamstone/blob/407b1948faab336a0e5fce3483fbf46e444e99fb/Source/Streamstone/Extensions.cs#L79-L109

**Comment by yevhen** [comment]
Looks like a bug. Don't think there any reason why it was omitted.

**Comment by yevhen** [comment]
Done!
