### ISSUE TITLE
Table per entity or per tenant?

### ISSUE THREAD

**Issue by LockTar** [yevhen/Streamstone#53]
Hi, 

We want some advice. 
We are creating a new application with SS. The application will be multi tenant (support multiple customers) solution.

Is it better to use SS with
-  a table per entity
- a table per tenant (customer of us) 
- a separate storage account for each tenant
etc

I think it's more a personal decision but maybe there are some limitations were we didn't think of yet. At the moment we only have the entity "Organisation" which is in fact a tenant/customer of us so this is really the time to make the right decision.

Thanks

**Comment by jkonecki** [comment]
I would discourage table per entity appraoch as it would increase maintenance. It will also prohibit you from making custom queries that span multiple entities (debugging, production issue investigations, etc)

Table per tenant is the approach I use as it allows for physical separation of tenant data and minimise maintenance by having to worry about 1 storage account for each environment.

I would go for storage account per tenant only if there will be multiple tables created for each tenant (with different data than events) as this makes keeping all data from each tenant clearly separated. There may be legal requirements for geographic location of tenant data - a multiple storage accounts in different regions may be needed. However, in this case I would still colocate multiple tenant tables in each storage account.

**Comment by LockTar** [comment]
> Table per tenant is the approach I use as it allows for physical separation of tenant data and minimise maintenance by having to worry about 1 storage account for each environment.

My idea was also for going into this direction. For multiple purposes. Like:

- Legal location to store data
- Easy to delete data for GDPR for particular customer
- Easy to delete data for complete customer

@jkonecki how about the "Organisation" it self? If you have a Storage Account per tenant (Organisation). Do you then have a property in your Organisation entity that points to a particular Storage Account? I would expect something like:
Master SS storage account that has all the organisations.
Per Organisation a separate storage account that is connected dynamically via the organisation "storage account name" property.

> I would go for storage account per tenant only if there will be multiple tables created for each tenant (with different data than events) as this makes keeping all data from each tenant clearly separated. There may be legal requirements for geographic location of tenant data - a multiple storage accounts in different regions may be needed. However, in this case I would still colocate multiple tenant tables in each storage account.

Just to confirm, your now saying not to go for SA per tenant?

**Comment by jkonecki** [comment]
At the moment I use table for tenant pattern. I only store 'tenant' in Organisation entity and the Storage Account connection string in an environment variable.
If you want to use 'storage account per entity' pattern than your Organisation entity would have to persist connection string.
I have a special 'infrastructure' tenant where I store the list of all organizations and related technical info.

My default approach is 'table for tenant' unless there are incompatible requirements like specific geolocation.

**Comment by yevhen** [comment]
Table per tenant +1

Table is a logical entity and a unit of operation. It’s much eaiser to delete everything tenant related (1-call) than with shared table design (you will need full partition scan and some background process)

**Comment by LockTar** [comment]
I think we are all thinking the same.

What about this suggestion as a best practice:
If you have a multi tenant setup than it is better to use a table per tenant. Each tenant table needs to be managed as well so a master table needs to be in place as well.

- One storage account
    - Master table with all the organisations/tenants
    - Table per tentant for application streams 

If physical separation of tenant data is required, you can create another storage account.

**Comment by yevhen** [comment]
@LockTar 👍
