### ISSUE TITLE
Many connections being opened

### ISSUE THREAD

**Issue by ghost** [yevhen/Streamstone#59]
Good afternoon,

I wanted to reach out as I am unsure if this is an issue, or a problem with my implementation. I am trying to modify many streams at one time in parallel, and when I do so my application is opening one connection per stream. This is problematic when deploying because I exhaust my connections quite rapidly. I am giving stream stone a singleton for cloud table storage, but it doesn't appear to be reusing it. The connections seem to open when calling Streamstone.Stream.TryOpenAsync(myPartition).

Any guidance on this would be greatly appreciated.

Thank you in advanced for your time.

**Comment by yevhen** [comment]
This is normal behavior when writing entities to multiple partitions in parallel for table storage API. 
Streamstone has nothing to do with that. You either need to bound (limit) the number of simultaneous writes or scale out to multiple machines. Doing heavy parallel IO can quickly exhaust the number of available sockets on a machine.

**Comment by ghost** [comment]
Thank you for your rapid response. I am actually having issues with the loads as opposed to the writes. When I attempt to load many data models in parallel from various streams that is when the socket exhaustion occurs.

EDIT
I see up above i didn't specify that. apologies.

**Comment by yevhen** [comment]
Ye, it makes no difference whether it's read or write. You're doing parallel IO and it's constrained by system resources. Either limit or scale up/scale out.

**Comment by ghost** [comment]
Gotcha. Thank you very much for your time sir. Your assistance was much appreciated.
