### ISSUE TITLE
streamstone.net offline

### ISSUE THREAD

**Issue by seniorquico** [yevhen/Streamstone#62]
More an FYI for anyone coming across the repo and trying to navigate to the project website... It appears the `streamstone.net` domain has gone offline. I recall the website only being a pretty version of the README. I don't believe we're missing anything, just broken links.

**Comment by yevhen** [comment]
Thanks! I forgot to pay for it ))

**Comment by yevhen** [comment]
Fixed

**Comment by seniorquico** [comment]
No worries. Thanks for keeping the lights on here. 😁
