### ISSUE TITLE
streamstone.net appears to be hijacked/hacked and is redirecting to scams & malware

### ISSUE THREAD

**Issue by lethek** [yevhen/Streamstone#65]
Pretty sure it's not my PC that is infected - I've tested in sandboxes on a couple of other PCs on different networks and got similar results.

**Comment by oscarlofwenhamn** [comment]
Is @yevhen the only maintainer able to update or remove the url? Feels like it would be good just to remove it from the repo for now, and then it could be re-added if/when it can be fixed and verified.

**Comment by yevhen** [comment]
ouch, I somehow missed the payment and now it's gone((

**Comment by yevhen** [comment]
done!
