### ISSUE TITLE
Migration to Azure.Data.Tables

### ISSUE THREAD

**Issue by dmshapoval** [yevhen/Streamstone#70]
Hi @yevhen , 
First of all, thanks for this package.
Could you please clarify whether it is expected to migrate it to Azure.Data.Tables, as according to the notification [here](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table) Microsoft.Azure.Cosmos.Table will not be supported after 3/31/2023

**Comment by yevhen** [comment]
Hi, @dmshapoval!

This was already [done](https://github.com/yevhen/Streamstone/pull/68) by amazing @sergiojrdotnet 

Just get latest version on Nuget

**Comment by dmshapoval** [comment]
Thanks
